services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: medusa_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: medusa-store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medusa_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medusa-store"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Redis
  redis:
    image: redis:7-alpine
    container_name: medusa_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - medusa_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Medusa Server
  # This service runs the Medusa backend application
  # and the admin dashboard.
  medusa:
    build: .
    container_name: medusa_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: sh -c "sleep 5 && sh ./start.sh"
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/medusa-store
      - REDIS_URL=redis://redis:6379
      - MIGRATE_ON_START=false
      - JWT_SECRET=${JWT_SECRET:-change-me-jwt}
      - COOKIE_SECRET=${COOKIE_SECRET:-change-me-cookie}
      - SESSION_COOKIE_NAME=${SESSION_COOKIE_NAME:-connect.sid}
      - ADMIN_CORS=${ADMIN_CORS:-https://ic-fix-medusa-admin-vercel.vercel.app,http://localhost:5173}
      - STORE_CORS=${STORE_CORS:-http://localhost:8000}
      - AUTH_CORS=${AUTH_CORS:-https://ic-fix-medusa-admin-vercel.vercel.app,http://localhost:5173}
      - TRUST_PROXY=${TRUST_PROXY:-1}
      - ADMIN_DISABLED=${ADMIN_DISABLED:-false}
    volumes:
      - .:/server
      - /server/node_modules
    networks:
      - medusa_network

volumes:
  postgres_data:

networks:
  medusa_network:
    driver: bridge


