name: CI/CD (GHCR)

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            # force 'latest' for pushes to main/master
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }},priority=100
            type=sha,prefix=sha-,format=short

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    # only deploy on main/master; don't reference secrets at job level
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      # Decide if we have all deploy secrets; expose as an output
      - name: Gate deploy by secrets
        id: gate
        run: |
          ok=true
          [ -z "${{ secrets.DEPLOY_HOST }}" ] && ok=false
          [ -z "${{ secrets.DEPLOY_USER }}" ] && ok=false
          [ -z "${{ secrets.DEPLOY_SSH_KEY }}" ] && ok=false
          echo "ok=$ok" >> "$GITHUB_OUTPUT"

      - name: Skip (secrets missing)
        if: ${{ steps.gate.outputs.ok != 'true' }}
        run: echo "Deploy secrets missing; skipping deploy."

      - name: Install SSH key
        if: ${{ steps.gate.outputs.ok == 'true' }}
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Add server to known_hosts
        if: ${{ steps.gate.outputs.ok == 'true' }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on server
        if: ${{ steps.gate.outputs.ok == 'true' }}
        run: |
          ssh -o StrictHostKeyChecking=no -o BatchMode=yes \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "\
              cd /opt/medusa && \
              docker compose pull && \
              docker compose up -d && \
              docker system prune -f \
            "
